### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by Zannark** [Zannark/CollegeProject_SurvivalGame#2]
Look into the rotation issue for the player. Something about it isn't quite right.

**Comment by SealabJaster** [comment]
Fixed rotation:
![2017-10-02_16-33-19](https://user-images.githubusercontent.com/3835574/31085703-d118bd42-a78f-11e7-9ffb-58aeb6786c94.gif)

Current broken rotation (From master):
![Uploading 2017-10-02_16-33-46.gif…]()
