### ISSUE TITLE
Navigation Node Spawning

### ISSUE THREAD

**Issue by Zannark** [Zannark/CollegeProject_SurvivalGame#7]
Navigation Nodes spawn on top of props. The props get iterated over but when the current prop is not in the same location of the node then it marks as false and pushes it back.

**Comment by SealabJaster** [comment]
Can close this now, it was fixed in https://github.com/Zannark/CollegeProject_SurvivalGame/commit/9f28263366f3a1456e53fd46c07de5651d3d2e36
