### ISSUE TITLE
Resources (yet again <3)

### ISSUE THREAD

**Issue by SealabJaster** [Zannark/CollegeProject_SurvivalGame#8]
Haven't actually looked at most of these myself (to any great detail, just enough to see if it's probably gonna be helpful to you)

# Collision/Physics
*Search terms used: 'basic 2d physics with rotation', 'rigid body dynamics'*
1. [How to create a custom 2d physics engine](https://gamedevelopment.tutsplus.com/tutorials/how-to-create-a-custom-2d-physics-engine-the-basics-and-impulse-resolution--gamedev-6331). Multi-part series, first demo video you may notice there's no rotation being applied to the physics, but that comes later on.
2. [Rigid Body Dynamics](http://chrishecker.com/Rigid_body_dynamics). More academic resource, since it was made before we were even born. (side note, rigid body dynamics itself seems to be a good google term)
3. [Basic 2D Vector Physics, Acceleration, Orientation, and Friction](http://www.randygaul.net/2012/02/22/basic-2d-vector-physics-acceleration-orientation-and-friction/). This may or may not be useful to you, it's more about movement rather then collision physics.
4. [Basic collision detection in 2D](http://devmag.org.za/2009/04/13/basic-collision-detection-in-2d-part-1/). Goes over circle collision, and bounding box collision(no rotation). You already have a library to handle this though.
5. [Intersecting polygons with rotation](https://stackoverflow.com/questions/2089173/non-axis-aligned-rectangle-intersection). Calculate the intersection of two rotated polygons.

# A*
*Search terms used: 'a* algorithm in 2d games', 'AI pathfinding 2D'*
1. [Introduction to A* pathfinding](https://www.raywenderlich.com/4946/introduction-to-a-pathfinding). Complete with a visual explanation, multiple different scenarios the algorithm will need to handle, and the algorithm laid out in pseudocode.

Will update more when I can be bothered

**Comment by Zannark** [comment]
Feeled betrayed, there was never anything updated :^)
